name: Daily Discord Joke

on:
  schedule:
    # 11:13 AM ART (14:13 UTC)
    - cron: '13 14 * * *'
    # 03:22 PM ART (18:22 UTC)
    - cron: '22 18 * * *'
  workflow_dispatch: # Para que puedas probarlo a mano cuando quieras

jobs:
  send-joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar Script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        run: node discord-sender.js